services:
    myapp:
      build: .
      container_name: myapp1
      ports:
        -8080:8080
      restart: always
      volume:
        my_app_volume: /app 
      enviroment:
      depends_on:
        - PostgreSQL
        - Redis
      networks:
        mynetw:
    PostgreSQL:
      image: postgres:16-alpine
      container_name: myapp1
      restart: always
      port: 
        - 5432:5432
      enviroment:
        POSTGRES_USER: ${ urluser }
        POSTGRES_PASSWORD: ${ urlpass }
        POSTGRES_DB: ${ urldb }

      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U urluser -d urldb"]
        interval: 10s
        timeout: 3s
        retries: 3
      volumes:
        my_app_volume: /var/lib/postgresql/data/

      networks:
        mynetw:

      
    Redis:
      image: postgres:16-alpine
      container_name: myapp1
      ports:
        - 6379:6379
      volumes:
        my_app_volume
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5


    pgAdmin:



volumes:
  my_app_volume:


networks:
  mynetw:
